### ISSUE TITLE
[Help wanted] Translate 'welcome-email' function from NodeJS to Python 🐍

### ISSUE THREAD

**Issue by Glide7** [appwrite/demos-for-functions#19]
## Translate 'welcome-email' function from NodeJS to Python 🐍
We use Appwrite Cloud Functions demos as a good way to show how Cloud Functions can be used with Appwrite, and also as a good starting point for developers wanting to write their new functions. 
Help us translate the cloud function ['welcome-email'](https://github.com/appwrite/demos-for-functions/tree/master/nodejs/welcome-email) from NodeJS to Python ☁

## Requirements 🔎
* For testing your code, you need a running Appwrite instance with cloud functions enabled. You’ll need to setup Appwrite from source using the `0.7.x` branch and Docker. 🐳
Clone the [appwrite/appwrite](https://github.com/appwrite/appwrite/tree/0.7.x) `0.7.x` branch. More instruction about how to start your Appwrite server from source are available [here](https://github.com/appwrite/appwrite/blob/0.7.x/CONTRIBUTING.md#setup-from-source). 📗

*  If this is your first PR for Appwrite, it is best to read some of our [contributions guidelines](https://github.com/appwrite/appwrite/blob/0.7.x/CONTRIBUTING.md).  ♥

*  For each target language we provide with a template for starting a new function. For Python you can use this [template](https://github.com/appwrite/demos-for-functions/blob/master/python/template/README.md) as your starting point.  🐍

**Comment by anushkrishnav** [comment]
I can work on this

**Comment by Glide7** [comment]
Awesome! @anushkrishnav - assigning you for this! please reach out if you have any questions 👍

**Comment by hack3r-0m** [comment]
I would like to take it

**Comment by Glide7** [comment]
@hack3r-0m checking if @anushkrishnav is done with this or not, and getting back to you

**Comment by anushkrishnav** [comment]
Really sorry got some heavy time crunch please assign it to hacker :)

**Comment by Glide7** [comment]
@hack3r-0m assigned it to you :)
