### ISSUE TITLE
Create a new user profile in "users" collection when a new account is created

### ISSUE THREAD

**Issue by gireeshp** [appwrite/demos-for-functions#288]
A demo to be created in Python function SDK which will create a new user profile in "users" collection of the DB when a new user account is created.

**Comment by jenniestrongbow** [comment]
A demo that shows how to write files on the server. Thanks

**Comment by jenniestrongbow** [comment]
A demo that show how to get the document ID of the document change that triggered the function. Thanks

**Comment by lohanidamodar** [comment]
1. You can create a separate issue for sample to write files on server, but you can use Appwrite's storage API to write file to server.
2. Whenever a function is triggered by system events, you get the payload in `APPWRITE_FUNCTION_EVENT_DATA` environment variable. which contains `$id` that is the id of the document.
