### ISSUE TITLE
📚 Documentation: Using variables

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/demos-for-functions#305]
### 💭 Description

Hi, 

I want to create a PHP function that is triggered when a document is added to a collection.

I know how to create pre-defined variables and how to get $_ENV variables in PHP. But how do I pass the document ID of the newly added document to the PHP function?

Thanks,

Nicolas

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
Hi, you already receive the whole newly created document in `APPWRITE_FUNCTION_EVENT_DATA` which includes the ID of the newly created document. More information: 
https://appwrite.io/docs/functions#enviromentVariables
