### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/demos-for-functions#307]
### 💭 Description

Hi,

I wrote a PHP function that writes a text file on my ubuntu server.

Can I write a text file anywhere on my server or am I restricted to a directory, if so, which one?

Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
Hey the functions itself are stateless, the files you write may not be accessible once the function has completed. We suggest to use Appwrite storage to store files from your functions. Let us know if you have further questions.

**Comment by stnguyen90** [comment]
Closing as question was answered and no further action required.
