### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by jenniestrongbow** [appwrite/demos-for-functions#308]
### 💭 Description

Hi,

How do you output text in the Logs on purpose ?

Thanks

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
You can send logs to stdout for the respective language. For example in dart you can use `print` in nodejs you can use `console.log` and so on
