### ISSUE TITLE
🐛 Bug Report: Demo Function (add updated at) running in loop

### ISSUE THREAD

**Issue by anandsubbu007** [appwrite/demos-for-functions#314]
### 👟 Reproduction steps

https://github.com/appwrite/appwrite/issues/3025#issue-1182524423

[add-updated-at](https://github.com/appwrite/demos-for-functions/tree/master/dart/add-updated-at)

Runs in loop Demo Function when tries to update the document [document.update]

### 👍 Expected behavior

-

### 👎 Actual Behavior

running in loop

### 🎲 Appwrite version

Version 0.10.x

### 💻 Operating system

Windows

### 🧱 Your Environment

Localhost

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by anandsubbu007** [comment]
Any update?

**Comment by stnguyen90** [comment]
Closing as duplicate.
